# Generated by Django 2.2.19 on 2021-03-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('lobby', 'lobby'), ('active', 'active'), ('close', 'close')], default='lobby', max_length=30),
        ),
    ]
