# Generated by Django 2.2.19 on 2021-03-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210306_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='state',
        ),
    ]
