# Generated by Django 2.2.19 on 2021-03-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_date',
        ),
    ]
