# Generated by Django 2.2.19 on 2021-03-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210306_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='state',
            new_name='game_state',
        ),
    ]
