# Generated by Django 2.2.19 on 2021-03-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210307_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='password',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
